services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    expose:
      - 3000
    #ports:
      #- 3000:3000
    volumes:
      - .:/data
    networks:
      - default
      - traefik_proxy
    environment:
      - FORCE_SSL=${DOMAIN:?DOMAIN not set}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docuseal.entrypoints=websecure"
      - "traefik.http.routers.docuseal.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.docuseal.tls.certresolver=http-challenge"

  postgres:
    image: postgres:15
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

#  caddy:
#    image: caddy:latest
#    command: caddy reverse-proxy --from $HOST --to app:3000
#    ports:
#      - 80:80
#      - 443:443
#      - 443:443/udp
#    volumes:
#      - .:/data
#    environment:
#      - HOST=${HOST}

networks:
  default:
  traefik_proxy:
    name: traefik_proxy
    external: true
